set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /MANIFEST:NO")
set(LIBRARY_OUTPUT_PATH "${CMAKE_CURRENT_LIST_DIR}")
cmake_policy(SET CMP0057 NEW)

message("CURLY-EUREKA INCLUDED...\nCURLY_EUREKA_DIR - ${CMAKE_CURRENT_LIST_DIR}")
set(CURLY_EUREKA_DIR ${CMAKE_CURRENT_LIST_DIR})

#configure gdh game ver
message("GAME_VERSION AVAILABLE VALUES NOW: 2.206")
if(DEFINED GAME_VERSION)
    message("NEW GAME_VERSION FOUND - ${GAME_VERSION}")
else()
    set(GAME_VERSION "2.206")
    message("GAME_VERSION ISN'T DEFINED, GAME_VERSION - ${GAME_VERSION}")
endif()

file(GLOB_RECURSE CURLY_EUREKA_SRC 
"${CURLY_EUREKA_DIR}/ce-main-src/*.cpp"
"${CURLY_EUREKA_DIR}/patterns/*.cpp"
)
message("CURLY_EUREKA_SRC: ${CURLY_EUREKA_SRC}")
    
set(CURLY_EUREKA_INCL
"${CURLY_EUREKA_DIR}"
"${CURLY_EUREKA_DIR}/ce-main-src"
"${CURLY_EUREKA_DIR}/patterns"
"${CURLY_EUREKA_DIR}/minhook-multihook/include"
"${CURLY_EUREKA_DIR}/gd.h_${GAME_VERSION}/"
"${CURLY_EUREKA_DIR}/gd.h_${GAME_VERSION}/include"
$IMGUI_HOOK_INCL
)
message("CURLY_EUREKA_INCL: ${CURLY_EUREKA_INCL}")

include_directories(${CURLY_EUREKA_INCL})

#EXCLUDE_MINHOOK?
if(DEFINED EXCLUDE_MINHOOK)
    message("FOUND EXCLUDE_MINHOOK DEFINTION, WILL NOT INCLUDED")
else()
    message("EXCLUDE_MINHOOK ISN'T DEFINED, WILL INCLUDED")
    add_subdirectory("${CURLY_EUREKA_DIR}/minhook-multihook" minhook-build)
    link_libraries(minhook)
endif()

#EXCLUDE_COCOS_HEADERS?
if(DEFINED EXCLUDE_COCOS_HEADERS)
    message("FOUND EXCLUDE_COCOS_HEADERS DEFINTION, WILL INCLUDED")
else()
    message("EXCLUDE_COCOS_HEADERS ISN'T DEFINED, WILL INCLUDED")
    add_subdirectory("${CURLY_EUREKA_DIR}/cocos-headers_${GAME_VERSION}" cocos-headers-build)
    link_libraries(cocos2d)
endif()